export const shopTableFields = [
  ['name', 'Наименование'],
  ['inn', 'ИНН'],
  ['director_name', 'Директор'],
  ['registered_at', 'Дата регистрации', 'date'],
  ['fns', 'ФНС'],
  ['sale_priority', 'Категория'],
  ['company_status', 'Статус'],
  ['ecsp_status', 'ЭЦП'],
  ['accounts_status', 'Наличие РС'],
  ['received_at', 'Дата приёма', 'date'],
  ['accountant_full_name', 'Бухгалтер'],
  ['sbis', 'СБИС'],
  ['edo_until', 'ЭДО дата окончания', 'date'],
  ['edo_id', 'ЭДО ID'],
  ['purchased_at', 'Дата покупки', 'date'],
  ['dirovod', 'Дировод'],
  ['failed_at', 'Дата слёта', 'date'],
  ['failure_reason', 'Причина слёта'],
  ['comment', 'Комментарий'],
] as const
