#!/usr/bin/env bash
# Generate Asterisk trunks/extensions from CRM DB and reload Asterisk.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
cd "$ROOT"

ENV_FILE="${ENV_FILE:-deploy/.env.staging}"
ASTERISK_DIR="${ASTERISK_DIR:-deploy/server/asterisk}"
POSTGRES_CONTAINER="${POSTGRES_CONTAINER:-crm-staging-postgres}"
ASTERISK_CONTAINER="${ASTERISK_CONTAINER:-crm-asterisk}"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "Env file not found: $ENV_FILE" >&2
  exit 1
fi

set -a
# shellcheck source=/dev/null
source "$ENV_FILE"
set +a

POSTGRES_USER="${POSTGRES_USER:-crm}"
POSTGRES_DB="${POSTGRES_DB:-crm}"

if [[ -z "${POSTGRES_PASSWORD:-}" || -z "${PGCRYPTO_KEY:-}" ]]; then
  echo "POSTGRES_PASSWORD and PGCRYPTO_KEY are required in $ENV_FILE" >&2
  exit 1
fi

mkdir -p "$ASTERISK_DIR"

tmp_pjsip="$(mktemp)"
tmp_ext="$(mktemp)"
trap 'rm -f "$tmp_pjsip" "$tmp_ext"' EXIT

cat > "$tmp_pjsip" <<'EOF'
; Generated by scripts/deploy/vps/telephony-sync.sh.
; Do not edit by hand; edit CRM telephony accounts instead.

EOF

cat > "$tmp_ext" <<'EOF'
; Generated by scripts/deploy/vps/telephony-sync.sh.
; Do not edit by hand; edit CRM telephony accounts instead.

EOF

account_sql="
SELECT
  id,
  regexp_replace(sip_host, '[^A-Za-z0-9._-]', '', 'g') AS sip_host,
  sip_port,
  CASE WHEN sip_transport IN ('udp','tcp') THEN sip_transport ELSE 'udp' END AS transport,
  sip_username,
  pgp_sym_decrypt(sip_password_encrypted, :'pgcrypto_key') AS sip_password,
  COALESCE(outbound_caller_id, '')
FROM telephony_accounts
WHERE is_active IS TRUE
ORDER BY id;
"

extension_sql="
SELECT
  e.account_id,
  regexp_replace(e.extension, '[^0-9A-Za-z*#+_-]', '', 'g') AS extension,
  pgp_sym_decrypt(e.password_encrypted, :'pgcrypto_key') AS extension_password,
  COALESCE(NULLIF(e.display_name, ''), u.full_name, u.username, u.email, e.extension) AS display_name
FROM telephony_extensions e
JOIN telephony_accounts a ON a.id = e.account_id
JOIN users u ON u.id = e.user_id
WHERE e.is_active IS TRUE
  AND a.is_active IS TRUE
ORDER BY e.account_id, e.extension;
"

accounts="$(
  docker exec -i -e PGPASSWORD="$POSTGRES_PASSWORD" "$POSTGRES_CONTAINER" \
    psql -v "pgcrypto_key=$PGCRYPTO_KEY" -U "$POSTGRES_USER" -d "$POSTGRES_DB" \
    -At -F $'\t' <<SQL
$account_sql
SQL
)"

extensions="$(
  docker exec -i -e PGPASSWORD="$POSTGRES_PASSWORD" "$POSTGRES_CONTAINER" \
    psql -v "pgcrypto_key=$PGCRYPTO_KEY" -U "$POSTGRES_USER" -d "$POSTGRES_DB" \
    -At -F $'\t' <<SQL
$extension_sql
SQL
)"

while IFS=$'\t' read -r account_id sip_host sip_port sip_transport sip_username sip_password caller_id; do
  [[ -n "${account_id:-}" ]] || continue
  trunk="bitcall-trunk-${account_id}"
  auth="bitcall-auth-${account_id}"
  aor="bitcall-aor-${account_id}"
  reg="bitcall-registration-${account_id}"
  transport="transport-${sip_transport}"

  cat >> "$tmp_pjsip" <<EOF
[${auth}]
type=auth
auth_type=userpass
username=${sip_username}
password=${sip_password}

[${aor}]
type=aor
contact=sip:${sip_host}:${sip_port}

[${trunk}]
type=endpoint
transport=${transport}
context=from-bitcall-${account_id}
disallow=all
allow=ulaw,alaw
outbound_auth=${auth}
aors=${aor}
from_user=${sip_username}
direct_media=no

[${reg}]
type=registration
transport=${transport}
outbound_auth=${auth}
server_uri=sip:${sip_host}:${sip_port}
client_uri=sip:${sip_username}@${sip_host}
contact_user=${sip_username}
retry_interval=60
forbidden_retry_interval=600
expiration=3600

EOF

  cat >> "$tmp_ext" <<EOF
[crm-internal-account-${account_id}]
exten => _X.,1,NoOp(CRM outbound via Bitcall account ${account_id}: \${EXTEN})
 same => n,Dial(PJSIP/\${EXTEN}@${trunk},60)
 same => n,Hangup()

EOF
done <<< "$accounts"

while IFS=$'\t' read -r account_id extension extension_password display_name; do
  [[ -n "${account_id:-}" && -n "${extension:-}" ]] || continue
  cat >> "$tmp_pjsip" <<EOF
[${extension}](webrtc-endpoint)
auth=${extension}
aors=${extension}
context=crm-internal-account-${account_id}
callerid=CRM ${extension} <${extension}>

[${extension}]
type=auth
auth_type=userpass
username=${extension}
password=${extension_password}

[${extension}]
type=aor
max_contacts=1
remove_existing=yes

EOF
done <<< "$extensions"

changed=0
if ! cmp -s "$tmp_pjsip" "$ASTERISK_DIR/pjsip.generated.conf"; then
  cp "$tmp_pjsip" "$ASTERISK_DIR/pjsip.generated.conf"
  changed=1
fi
if ! cmp -s "$tmp_ext" "$ASTERISK_DIR/extensions.generated.conf"; then
  cp "$tmp_ext" "$ASTERISK_DIR/extensions.generated.conf"
  changed=1
fi

if [[ "$changed" -eq 1 ]]; then
  docker exec "$ASTERISK_CONTAINER" asterisk -rx "pjsip reload" >/dev/null
  docker exec "$ASTERISK_CONTAINER" asterisk -rx "dialplan reload" >/dev/null
  echo "Asterisk config synced and reloaded."
else
  echo "Asterisk config already up to date."
fi
