#!/usr/bin/env bash
# Generate Asterisk trunks/extensions from CRM DB and reload Asterisk.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
cd "$ROOT"

ENV_FILE="${ENV_FILE:-deploy/.env.staging}"
ASTERISK_DIR="${ASTERISK_DIR:-deploy/server/asterisk}"
POSTGRES_CONTAINER="${POSTGRES_CONTAINER:-crm-staging-postgres}"
ASTERISK_CONTAINER="${ASTERISK_CONTAINER:-crm-asterisk}"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "Env file not found: $ENV_FILE" >&2
  exit 1
fi

set -a
# shellcheck source=/dev/null
source "$ENV_FILE"
set +a

POSTGRES_USER="${POSTGRES_USER:-crm}"
POSTGRES_DB="${POSTGRES_DB:-crm}"

if [[ -z "${POSTGRES_PASSWORD:-}" || -z "${PGCRYPTO_KEY:-}" ]]; then
  echo "POSTGRES_PASSWORD and PGCRYPTO_KEY are required in $ENV_FILE" >&2
  exit 1
fi

mkdir -p "$ASTERISK_DIR"

tmp_pjsip="$(mktemp)"
tmp_ext="$(mktemp)"
trap 'rm -f "$tmp_pjsip" "$tmp_ext"' EXIT

cat > "$tmp_pjsip" <<'EOF'
; Generated by scripts/deploy/vps/telephony-sync.sh.
; Do not edit by hand; edit CRM telephony accounts instead.

EOF

cat > "$tmp_ext" <<'EOF'
; Generated by scripts/deploy/vps/telephony-sync.sh.
; Do not edit by hand; edit CRM telephony accounts instead.

EOF

# Unit separator (0x1f) avoids breakage when passwords/names contain tabs/spaces.
# Passwords via pgp_sym_decrypt_bytea + base64 (avoids UTF8 null-byte errors).
account_sql="
SELECT
  id,
  regexp_replace(sip_host, '[^A-Za-z0-9._-]', '', 'g') AS sip_host,
  sip_port,
  CASE WHEN sip_transport IN ('udp','tcp') THEN sip_transport ELSE 'udp' END AS transport,
  sip_username,
  encode(pgp_sym_decrypt_bytea(sip_password_encrypted, :'pgcrypto_key'), 'base64'),
  encode(convert_to(COALESCE(outbound_caller_id, ''), 'UTF8'), 'base64')
FROM telephony_accounts
WHERE is_active IS TRUE
ORDER BY id;
"

extension_sql="
SELECT
  e.account_id,
  regexp_replace(e.extension, '[^0-9A-Za-z*#+_-]', '', 'g') AS extension,
  encode(pgp_sym_decrypt_bytea(e.password_encrypted, :'pgcrypto_key'), 'base64'),
  encode(
    convert_to(
      translate(
        COALESCE(NULLIF(e.display_name, ''), u.full_name, u.username, u.email, e.extension),
        chr(9) || chr(10) || chr(13),
        '   '
      ),
      'UTF8'
    ),
    'base64'
  )
FROM telephony_extensions e
JOIN telephony_accounts a ON a.id = e.account_id
JOIN users u ON u.id = e.user_id
WHERE e.is_active IS TRUE
  AND a.is_active IS TRUE
ORDER BY e.account_id, e.extension;
"

b64_decode() {
  # portable: busybox/openssl/base64
  if command -v base64 >/dev/null 2>&1; then
    printf '%s' "$1" | base64 -d 2>/dev/null || printf '%s' "$1" | base64 -D 2>/dev/null
  else
    printf '%s' "$1" | openssl base64 -d -A
  fi
}

accounts="$(
  docker exec -i -e PGPASSWORD="$POSTGRES_PASSWORD" "$POSTGRES_CONTAINER" \
    psql -v ON_ERROR_STOP=1 -v "pgcrypto_key=$PGCRYPTO_KEY" \
    -U "$POSTGRES_USER" -d "$POSTGRES_DB" \
    -At -F $'\x1f' <<SQL
$account_sql
SQL
)"

extensions="$(
  docker exec -i -e PGPASSWORD="$POSTGRES_PASSWORD" "$POSTGRES_CONTAINER" \
    psql -v ON_ERROR_STOP=1 -v "pgcrypto_key=$PGCRYPTO_KEY" \
    -U "$POSTGRES_USER" -d "$POSTGRES_DB" \
    -At -F $'\x1f' <<SQL
$extension_sql
SQL
)"

account_count=0
while IFS=$'\x1f' read -r account_id sip_host sip_port sip_transport sip_username sip_password_b64 caller_id_b64; do
  [[ -n "${account_id:-}" ]] || continue
  sip_password="$(b64_decode "$sip_password_b64")"
  caller_id="$(b64_decode "${caller_id_b64:-}")"
  trunk="bitcall-trunk-${account_id}"
  auth="bitcall-auth-${account_id}"
  aor="bitcall-aor-${account_id}"
  reg="bitcall-registration-${account_id}"
  transport="transport-${sip_transport}"
  account_count=$((account_count + 1))

  # Quote-safe writes: passwords may contain $ # ; etc.
  {
    printf '[%s]\n' "$auth"
    printf 'type=auth\n'
    printf 'auth_type=userpass\n'
    printf 'username=%s\n' "$sip_username"
    printf 'password=%s\n' "$sip_password"
    printf '\n'
    printf '[%s]\n' "$aor"
    printf 'type=aor\n'
    printf 'contact=sip:%s:%s\n' "$sip_host" "$sip_port"
    printf '\n'
    printf '[%s]\n' "$trunk"
    printf 'type=endpoint\n'
    printf 'transport=%s\n' "$transport"
    printf 'context=from-bitcall-%s\n' "$account_id"
    printf 'disallow=all\n'
    printf 'allow=ulaw,alaw\n'
    printf 'outbound_auth=%s\n' "$auth"
    printf 'aors=%s\n' "$aor"
    printf 'from_user=%s\n' "$sip_username"
    printf 'direct_media=no\n'
    printf '\n'
    printf '[%s]\n' "$reg"
    printf 'type=registration\n'
    printf 'transport=%s\n' "$transport"
    printf 'outbound_auth=%s\n' "$auth"
    printf 'server_uri=sip:%s:%s\n' "$sip_host" "$sip_port"
    printf 'client_uri=sip:%s@%s\n' "$sip_username" "$sip_host"
    printf 'contact_user=%s\n' "$sip_username"
    printf 'retry_interval=60\n'
    printf 'forbidden_retry_interval=600\n'
    printf 'expiration=3600\n'
    printf '\n'
  } >> "$tmp_pjsip"

  {
    printf '[crm-internal-account-%s]\n' "$account_id"
    printf 'exten => _+X.,1,NoOp(CRM outbound via Bitcall account %s: ${EXTEN})\n' "$account_id"
    printf ' same => n,Dial(PJSIP/${EXTEN}@%s,60)\n' "$trunk"
    printf ' same => n,Hangup()\n'
    printf '\n'
    printf 'exten => _X.,1,NoOp(CRM outbound via Bitcall account %s: ${EXTEN})\n' "$account_id"
    printf ' same => n,Dial(PJSIP/${EXTEN}@%s,60)\n' "$trunk"
    printf ' same => n,Hangup()\n'
    printf '\n'
  } >> "$tmp_ext"
done <<< "$accounts"

extension_count=0
extension_list=""
while IFS=$'\x1f' read -r account_id extension extension_password_b64 display_name_b64; do
  [[ -n "${account_id:-}" && -n "${extension:-}" ]] || continue
  extension_password="$(b64_decode "$extension_password_b64")"
  display_name="$(b64_decode "${display_name_b64:-}")"
  extension_count=$((extension_count + 1))
  if [[ -n "$extension_list" ]]; then
    extension_list+=","
  fi
  extension_list+="$extension"

  {
    printf '[%s](webrtc-endpoint)\n' "$extension"
    printf 'auth=%s\n' "$extension"
    printf 'aors=%s\n' "$extension"
    printf 'context=crm-internal-account-%s\n' "$account_id"
    printf 'callerid=CRM %s <%s>\n' "$extension" "$extension"
    printf '\n'
    printf '[%s]\n' "$extension"
    printf 'type=auth\n'
    printf 'auth_type=userpass\n'
    printf 'username=%s\n' "$extension"
    printf 'password=%s\n' "$extension_password"
    printf '\n'
    printf '[%s]\n' "$extension"
    printf 'type=aor\n'
    printf 'max_contacts=1\n'
    printf 'remove_existing=yes\n'
    printf '\n'
  } >> "$tmp_pjsip"
done <<< "$extensions"

echo "telephony-sync: accounts=${account_count} extensions=${extension_count} [${extension_list:-none}]"

if [[ "$account_count" -lt 1 ]]; then
  echo "telephony-sync: abort — no active telephony accounts (refusing to overwrite Asterisk config)" >&2
  exit 1
fi
if [[ "$extension_count" -lt 1 ]]; then
  echo "telephony-sync: warning — no active extensions in DB" >&2
fi

changed=0
if ! cmp -s "$tmp_pjsip" "$ASTERISK_DIR/pjsip.generated.conf"; then
  cp "$tmp_pjsip" "$ASTERISK_DIR/pjsip.generated.conf"
  chmod 0644 "$ASTERISK_DIR/pjsip.generated.conf"
  changed=1
fi
if ! cmp -s "$tmp_ext" "$ASTERISK_DIR/extensions.generated.conf"; then
  cp "$tmp_ext" "$ASTERISK_DIR/extensions.generated.conf"
  chmod 0644 "$ASTERISK_DIR/extensions.generated.conf"
  changed=1
fi

if [[ "$changed" -eq 1 ]]; then
  docker exec "$ASTERISK_CONTAINER" asterisk -rx "pjsip reload" >/dev/null
  docker exec "$ASTERISK_CONTAINER" asterisk -rx "dialplan reload" >/dev/null
  echo "Asterisk config synced and reloaded."
else
  echo "Asterisk config already up to date."
fi
