from __future__ import annotations

PIPELINE_NEW_CODE = "new"
PIPELINE_IN_PROGRESS_CODE = "in_progress"
PIPELINE_WON_CODE = "won"
PIPELINE_LOST_CODE = "lost"

PIPELINE_DEFAULT_OPEN_CODES = frozenset({PIPELINE_NEW_CODE, PIPELINE_IN_PROGRESS_CODE})
PIPELINE_TERMINAL_CODES = frozenset({PIPELINE_WON_CODE, PIPELINE_LOST_CODE})
PIPELINE_HIDDEN_ADMIN_CODES = frozenset({PIPELINE_WON_CODE, PIPELINE_LOST_CODE})
PIPELINE_PROTECTED_DELETE_CODES = frozenset(
    {
        PIPELINE_NEW_CODE,
        PIPELINE_IN_PROGRESS_CODE,
        PIPELINE_WON_CODE,
        PIPELINE_LOST_CODE,
    },
)
